# Generated by Django 6.0.5 on 2026-05-30 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='app1s/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ML', 'MOBILE_LEAGE'), ('FF', 'FREE_FIRE'), ('YT', 'YOUTUBE'), ('VS', 'VSCODE'), ('WA', 'WHATSAPP')], max_length=2)),
            ],
        ),
    ]
