# Generated by Django 6.0.5 on 2026-06-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appvarity',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='appvarity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
